from django.core.management.base import BaseCommand
from core.models import Category, Collection, Tags, ChatbotKeyword
from django.utils.text import slugify


class Command(BaseCommand):
    help = "Seed chatbot keywords for product recommendation engine"

    def handle(self, *args, **kwargs):
        seeds = [
            # Main categories
            {"keyword": "brass idols", "category": "idols-and-statues", "priority": 20},
            {"keyword": "idol", "category": "idols-and-statues", "priority": 15},
            {"keyword": "idols", "category": "idols-and-statues", "priority": 15},
            {"keyword": "home decor", "category": "home-decor", "priority": 20},
            {"keyword": "decor", "category": "home-decor", "priority": 12},
            {"keyword": "pooja essentials", "category": "pooja-essentials", "priority": 20},
            {"keyword": "pooja", "category": "pooja-essentials", "priority": 15},
            {"keyword": "puja", "category": "pooja-essentials", "priority": 15},
            {"keyword": "kitchen essentials", "category": "kitchen-essentials", "priority": 20},
            {"keyword": "kitchen", "category": "kitchen-essentials", "priority": 15},
            {"keyword": "gifting", "category": "gifting-items", "priority": 20},
            {"keyword": "gift", "category": "gifting-items", "priority": 15},

            # Subcategories
            {"keyword": "god", "category": "god", "priority": 20},
            {"keyword": "lord", "category": "god", "priority": 20},
            {"keyword": "goddess", "category": "goddess", "priority": 15},
            {"keyword": "devi", "category": "goddess", "priority": 15},
            {"keyword": "mata", "category": "goddess", "priority": 15},
            {"keyword": "matha", "category": "goddess", "priority": 15},
            {"keyword": "stone idols", "category": "stone-idols", "priority": 15},
            {"keyword": "gomatha", "category": "gomatha", "priority": 20},
            {"keyword": "gomata", "category": "gomatha", "priority": 20},
            {"keyword": "gaumata", "category": "gomatha", "priority": 20},
            {"keyword": "wax casting", "category": "wax-casting-idols", "priority": 12},
            {"keyword": "wax casting idols", "category": "wax-casting-idols", "priority": 20},
            {"keyword": "wax casting idol", "category": "wax-casting-idols", "priority": 20},
            {"keyword": "divine pair", "category": "divine-pair", "priority": 15},

            # Idol collections
            {"keyword": "narsimha", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "narsimham", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "narasimha", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "lord narsimha", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "lord narsimham", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "lord narasimha", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "narsimha swami", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "narasimha swami", "collection": "lord-narsimha", "priority": 100},
            {"keyword": "laddu gopal", "collection": "laddu-gopal", "priority": 100},
            {"keyword": "chhote krishna", "collection": "laddu-gopal", "priority": 100},
            {"keyword": "laddu gopal", "collection": "laddu-gopal-wax-casting", "priority": 90},
            {"keyword": "chhote krishna", "collection": "laddu-gopal-wax-casting", "priority": 90},
            {"keyword": "lord hanuman", "collection": "lord-hanuman", "priority": 100},
            {"keyword": "hanuman", "collection": "lord-hanuman", "priority": 100},
            {"keyword": "bajrangbali", "collection": "lord-hanuman", "priority": 100},
            {"keyword": "nataraj", "collection": "nataraj-swami", "priority": 100},
            {"keyword": "nataraja", "collection": "nataraj-swami", "priority": 100},
            {"keyword": "nataraj swami", "collection": "nataraj-swami", "priority": 100},
            {"keyword": "khatu shyam", "collection": "khatu-shyam-baba", "priority": 100},
            {"keyword": "khatu shyam baba", "collection": "khatu-shyam-baba", "priority": 100},
            {"keyword": "khatu shyam", "collection": "khatu-shyam-stone-idols", "priority": 90},
            {"keyword": "khatu shyam baba", "collection": "khatu-shyam-stone-idols", "priority": 90},
            {"keyword": "ganesha", "collection": "lord-ganesha", "priority": 100},
            {"keyword": "ganapati", "collection": "lord-ganesha", "priority": 100},
            {"keyword": "ganesh", "collection": "lord-ganesha", "priority": 100},
            {"keyword": "ganesha", "collection": "lord-ganesha-stone-idols", "priority": 90},
            {"keyword": "ganapati", "collection": "lord-ganesha-stone-idols", "priority": 90},
            {"keyword": "ganesh", "collection": "lord-ganesha-stone-idols", "priority": 90},
            {"keyword": "ganesha", "collection": "lord-ganesha-wax-casting", "priority": 80},
            {"keyword": "ganapati", "collection": "lord-ganesha-wax-casting", "priority": 80},
            {"keyword": "ganesh", "collection": "lord-ganesha-wax-casting", "priority": 80},
            {"keyword": "ganesha", "collection": "lord-ganesha-wax-casting-silver", "priority": 70},
            {"keyword": "ganapati", "collection": "lord-ganesha-wax-casting-silver", "priority": 70},
            {"keyword": "ganesh", "collection": "lord-ganesha-wax-casting-silver", "priority": 70},
            {"keyword": "krishna", "collection": "lord-krishna", "priority": 100},
            {"keyword": "lord krishna", "collection": "lord-krishna", "priority": 100},
            {"keyword": "krishn", "collection": "lord-krishna", "priority": 100},
            {"keyword": "lord krishn", "collection": "lord-krishna", "priority": 100},
            {"keyword": "kisna", "collection": "lord-krishna", "priority": 100},
            {"keyword": "kanha", "collection": "lord-krishna", "priority": 100},
            {"keyword": "kanhaiya", "collection": "lord-krishna", "priority": 100},
            {"keyword": "murugan", "collection": "lord-murugan", "priority": 100},
            {"keyword": "lord murugan", "collection": "lord-murugan", "priority": 100},
            {"keyword": "ayappa", "collection": "ayappa-swami", "priority": 100},
            {"keyword": "ayappa swami", "collection": "ayappa-swami", "priority": 100},
            {"keyword": "ayappa", "collection": "ayappa-swami-wax-casting", "priority": 90},
            {"keyword": "ayappa swami", "collection": "ayappa-swami-wax-casting", "priority": 90},
            {"keyword": "balaji", "collection": "lord-balaji", "priority": 100},
            {"keyword": "lord balaji", "collection": "lord-balaji", "priority": 100},
            {"keyword": "balaji", "collection": "lord-balaji-stone-idols", "priority": 90},
            {"keyword": "lord balaji", "collection": "lord-balaji-stone-idols", "priority": 90},
            {"keyword": "khandoba", "collection": "shri-khandoba", "priority": 100},
            {"keyword": "shri khandoba", "collection": "shri-khandoba", "priority": 100},
            {"keyword": "ram", "collection": "shri-ram", "priority": 100},
            {"keyword": "lord ram", "collection": "shri-ram", "priority": 100},
            {"keyword": "rama", "collection": "shri-ram", "priority": 100},
            {"keyword": "lord rama", "collection": "shri-ram", "priority": 100},
            {"keyword": "shri rama", "collection": "shri-ram", "priority": 100},
            {"keyword": "shiva", "collection": "lord-shiva", "priority": 100},
            {"keyword": "lord shiva", "collection": "lord-shiva", "priority": 100},
            {"keyword": "dattatreya", "collection": "lord-dattatreya", "priority": 100},
            {"keyword": "lord dattatreya", "collection": "lord-dattatreya", "priority": 100},
            {"keyword": "kartikeya", "collection": "lord-kartikeya", "priority": 100},
            {"keyword": "lord kartikeya", "collection": "lord-kartikeya", "priority": 100},
            {"keyword": "karthikeya", "collection": "lord-kartikeya", "priority": 100},
            {"keyword": "lord karthikeya", "collection": "lord-kartikeya", "priority": 100},
            {"keyword": "vishnu", "collection": "lord-vishnu", "priority": 100},
            {"keyword": "lord vishnu", "collection": "lord-vishnu", "priority": 100},
            {"keyword": "sai", "collection": "sri-sai-baba", "priority": 100},
            {"keyword": "sai baba", "collection": "sri-sai-baba", "priority": 100},
            {"keyword": "sri sai baba", "collection": "sri-sai-baba", "priority": 100},
            {"keyword": "saraswati", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswati devi", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswathi", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswathi devi", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswati maata", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswati maatha", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswathi mata", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswathi matha", "collection": "saraswati-devi", "priority": 100},
            {"keyword": "saraswati", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswati devi", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswathi", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswathi devi", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswati maata", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswati maatha", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswathi mata", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "saraswathi matha", "collection": "saraswati-devi-stone-idols", "priority": 90},
            {"keyword": "renuka", "collection": "renuka-maata", "priority": 100},
            {"keyword": "renuka maata", "collection": "renuka-maata", "priority": 100},
            {"keyword": "renuka maatha", "collection": "renuka-maata", "priority": 100},
            {"keyword": "renuka mata", "collection": "renuka-maata", "priority": 100},
            {"keyword": "renuka matha", "collection": "renuka-maata", "priority": 100},
            {"keyword": "lakshmi", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "lakshmi devi", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "lakshmi maata", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "lakshmi maatha", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "lakshmi mata", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "lakshmi matha", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "laxmi", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "laxmi devi", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "laxmi maata", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "laxmi maatha", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "laxmi mata", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "laxmi matha", "collection": "lakshmi-devi", "priority": 100},
            {"keyword": "lakshmi", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "lakshmi devi", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "laxmi", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "laxmi devi", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "lakshmi maata", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "lakshmi maatha", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "laxmi mata", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "laxmi matha", "collection": "lakshmi-devi-stone-idols", "priority": 90},
            {"keyword": "lakshmi", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "lakshmi devi", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "laxmi", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "laxmi devi", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "lakshmi maata", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "lakshmi maatha", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "laxmi mata", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "laxmi matha", "collection": "lakshmi-devi-wax-casting", "priority": 80},
            {"keyword": "lakshmi", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "lakshmi devi", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "laxmi", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "laxmi devi", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "lakshmi maata", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "lakshmi maatha", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "laxmi mata", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "laxmi matha", "collection": "lakshmi-devi-wax-casting-silver", "priority": 80},
            {"keyword": "annapurana", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurana devi", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurna", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurna devi", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurana maata", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurana maatha", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurna mata", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "annapurna matha", "collection": "annapurna-devi", "priority": 100},
            {"keyword": "lalita", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalita maata", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalita maatha", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalita mata", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalita matha", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalitha maata", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalitha maatha", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalitha mata", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "lalitha matha", "collection": "lalitha-maata", "priority": 100},
            {"keyword": "radha", "collection": "radha-devi", "priority": 100},
            {"keyword": "radha devi", "collection": "radha-devi", "priority": 100},
            {"keyword": "karumari amman", "collection": "karumari-amman", "priority": 100},
            {"keyword": "durga", "collection": "durga-maata", "priority": 100},
            {"keyword": "durga maata", "collection": "durga-maata", "priority": 100},
            {"keyword": "durga maatha", "collection": "durga-maata", "priority": 100},
            {"keyword": "durga mata", "collection": "durga-maata", "priority": 100},
            {"keyword": "durga matha", "collection": "durga-maata", "priority": 100},
            {"keyword": "durga devi", "collection": "durga-maata", "priority": 100},
            {"keyword": "devi durga", "collection": "durga-maata", "priority": 100},
            {"keyword": "gomatha", "collection": "gomatha", "priority": 100},
            {"keyword": "gomata", "collection": "gomatha", "priority": 100},
            {"keyword": "gaumata", "collection": "gomatha", "priority": 100},
            {"keyword": "gomatha", "collection": "gomatha-stone", "priority": 90},
            {"keyword": "gomata", "collection": "gomatha-stone", "priority": 90},
            {"keyword": "gaumata", "collection": "gomatha-stone", "priority": 90},
            {"keyword": "gomatha wax casting", "collection": "gomatha-wax-casting-idols", "priority": 100},
            {"keyword": "gomata wax casting", "collection": "gomatha-wax-casting-idols", "priority": 100},
            {"keyword": "gomatha", "collection": "gomatha-wax-casting-idols", "priority": 80},
            {"keyword": "gomata", "collection": "gomatha-wax-casting-idols", "priority": 80},
            {"keyword": "gaumata", "collection": "gomatha-wax-casting-idols", "priority": 80},
            {"keyword": "radha krishna", "collection": "radha-krishna", "priority": 100},
            {"keyword": "radha krishna", "collection": "radha-krishna-stone-idols", "priority": 90},
            {"keyword": "ganesh lakshmi", "collection": "ganesh-lakshmi-stone-idols", "priority": 90},
            {"keyword": "ganesh lakshmi", "collection": "ganesh-lakshmi-wax-casting", "priority": 80},
            {"keyword": "vishnu lakshmi", "collection": "vishnu-lakshmi", "priority": 100},
            {"keyword": "ram sita", "collection": "shri-ram-sita-darbar", "priority": 100},
            {"keyword": "shri ram sita", "collection": "shri-ram-sita-darbar", "priority": 100},
            {"keyword": "ram seeta", "collection": "shri-ram-sita-darbar", "priority": 100},
            {"keyword": "shri ram seeta", "collection": "shri-ram-sita-darbar", "priority": 100},
            {"keyword": "ram darbar", "collection": "shri-ram-sita-darbar", "priority": 100},

            # Home decor collections
            {"keyword": "urli", "category": "urli", "priority": 60},
            {"keyword": "wall decor", "category": "wall-decor", "priority": 60},
            {"keyword": "table decor", "category": "table-decor", "priority": 60},
            {"keyword": "urli bowl", "collection": "urli", "priority": 100},
            {"keyword": "urli", "collection": "urli", "priority": 100},
            {"keyword": "urli", "collection": "elephant-urli", "priority": 90},
            {"keyword": "elephant urli", "collection": "elephant-urli", "priority": 100},
            {"keyword": "vintage", "collection": "vintage-collection", "priority": 100},
            {"keyword": "vintage collection", "collection": "vintage-collection", "priority": 100},
            {"keyword": "vintage decor", "collection": "vintage-collection", "priority": 100},
            {"keyword": "divine symbols", "collection": "divine-symbols-collection", "priority": 100},
            {"keyword": "divine symbols collection", "collection": "divine-symbols-collection", "priority": 100},
            {"keyword": "divine symbol", "collection": "divine-symbols-collection", "priority": 100},
            {"keyword": "sacred heritage", "collection": "sacred-heritage-collection", "priority": 100},
            {"keyword": "sacred heritage decor", "collection": "sacred-heritage-collection", "priority": 100},
            {"keyword": "spiritual decor", "collection": "spiritual-decor-collection", "priority": 100},
            {"keyword": "festival wall decor", "collection": "festive-wall-decor", "priority": 100},

            # Pooja collections
            {"keyword": "hanging diyas", "collection": "hanging-diyas", "priority": 100},
            {"keyword": "hanging diya", "collection": "hanging-diyas", "priority": 100},
            {"keyword": "diya", "category": "diyas-and-lamps", "priority": 70},
            {"keyword": "diyas", "category": "diyas-and-lamps", "priority": 70},
            {"keyword": "diya", "collection": "diya-wax-casting", "priority": 70},
            {"keyword": "diyas", "collection": "diya-wax-casting", "priority": 70},
            {"keyword": "akhanda diya", "collection": "akhanda-collection", "priority": 100},
            {"keyword": "akhanda diyas", "collection": "akhanda-collection", "priority": 100},
            {"keyword": "diya", "collection": "ritual-essentials", "priority": 60},
            {"keyword": "diyas", "collection": "ritual-essentials", "priority": 60},
            {"keyword": "lamp", "collection": "ritual-essentials", "priority": 100},
            {"keyword": "diwali diya", "collection": "decorative-lamps", "priority": 100},
            {"keyword": "diwali diyas", "collection": "decorative-lamps", "priority": 100},
            {"keyword": "decorative diya", "collection": "decorative-lamps", "priority": 100},
            {"keyword": "decorative diyas", "collection": "decorative-lamps", "priority": 100},
            {"keyword": "festival diya", "collection": "decorative-lamps", "priority": 100},
            {"keyword": "festival diyas", "collection": "decorative-lamps", "priority": 100},
            {"keyword": "festival diya", "collection": "festive-lighting-collection", "priority": 90},
            {"keyword": "festival diyas", "collection": "festive-lighting-collection", "priority": 90},
            {"keyword": "lamp", "category": "diyas-and-lamps", "priority": 60},
            {"keyword": "kalash", "category": "kalash", "priority": 80},
            {"keyword": "lota", "category": "kalash", "priority": 80},
            {"keyword": "kalash", "collection": "kalash-lota", "priority": 100},
            {"keyword": "lota", "collection": "kalash-lota", "priority": 100},
            {"keyword": "chowki", "collection": "chowki", "priority": 100},
            {"keyword": "chowki", "category": "chowki", "priority": 80},
            {"keyword": "asan", "collection": "singhasan", "priority": 100},
            {"keyword": "singhasan", "collection": "singhasan", "priority": 100},
            {"keyword": "asan", "category": "asan", "priority": 80},
            {"keyword": "bell", "category": "bells", "priority": 80},
            {"keyword": "bell", "collection": "bells", "priority": 100}, # pending
            {"keyword": "pooja bell", "collection": "bells", "priority": 100}, # pending
            {"keyword": "brass bell", "collection": "bells", "priority": 100}, # pending
            {"keyword": "copper sadaari", "collection": "copper-sadaari", "priority": 100},
            {"keyword": "sadaari", "collection": "copper-sadaari", "priority": 90},

            # Kitchen collections
            {"keyword": "cookware", "category": "cookware", "priority": 70},
            {"keyword": "serveware", "category": "serveware", "priority": 70},
            {"keyword": "drinkware", "category": "drinkware", "priority": 70},
            {"keyword": "cooking pot", "collection": "cooking-pot", "priority": 100},
            {"keyword": "serving pot", "collection": "cooking-and-serve-pot", "priority": 100},
            {"keyword": "cooking serve pot", "collection": "cooking-and-serve-pot", "priority": 100},
            {"keyword": "cup saucer", "collection": "cup-and-saucer", "priority": 100},
            {"keyword": "cup and saucer", "collection": "cup-and-saucer", "priority": 100},
            {"keyword": "tea pot", "collection": "tea-pot", "priority": 100},
            {"keyword": "ghee pot", "collection": "ghee-pot", "priority": 100},
            {"keyword": "mug", "collection": "mug", "priority": 100},
            {"keyword": "glass", "collection": "glass", "priority": 100},

            # Gifting
            {"keyword": "gift hamper", "collection": "gift-hamper", "priority": 100},
            {"keyword": "diwali gifts", "collection": "diwali", "priority": 100},
            {"keyword": "diwali gift", "collection": "diwali", "priority": 100},
            {"keyword": "holi gifts", "collection": "holi", "priority": 100},
            {"keyword": "holi gift", "collection": "holi", "priority": 100},
            {"keyword": "onam gifts", "collection": "onam", "priority": 100},
            {"keyword": "onam gift", "collection": "onam", "priority": 100},
            {"keyword": "ganesh chaturthi gifts", "collection": "ganesh-chaturthi", "priority": 100},
            {"keyword": "ganesh chaturthi gift", "collection": "ganesh-chaturthi", "priority": 100},
            {"keyword": "ganesh puja gifts", "collection": "ganesh-chaturthi", "priority": 100},
            {"keyword": "ganesh puja gift", "collection": "ganesh-chaturthi", "priority": 100},
            {"keyword": "navratri gifts", "collection": "navratri", "priority": 100},
            {"keyword": "navratri gift", "collection": "navratri", "priority": 100},
            {"keyword": "dussehra gifts", "collection": "dussehra", "priority": 100},
            {"keyword": "dussehra gift", "collection": "dussehra", "priority": 100},
            {"keyword": "janmashtami gifts", "collection": "janmashtami", "priority": 100},
            {"keyword": "janmashtami gift", "collection": "janmashtami", "priority": 100},
            {"keyword": "rakhi gifts", "collection": "happy-rakhi", "priority": 100},
            {"keyword": "rakhi gift", "collection": "happy-rakhi", "priority": 100},
            {"keyword": "rakshabandhan gifts", "collection": "happy-rakhi", "priority": 100},
            {"keyword": "rakshabandhan gift", "collection": "happy-rakhi", "priority": 100},
            {"keyword": "work annivarsary", "collection": "work-annivarsary", "priority": 100},
            {"keyword": "work annivarsary gifts", "collection": "work-annivarsary", "priority": 100},
            {"keyword": "work annivarsary gift", "collection": "work-annivarsary", "priority": 100},
            {"keyword": "wedding annivarsary", "collection": "wedding-anniversary", "priority": 100},
            {"keyword": "wedding annivarsary gifts", "collection": "wedding-anniversary", "priority": 100},
            {"keyword": "wedding annivarsary gift", "collection": "wedding-anniversary", "priority": 100},
            {"keyword": "house warming", "collection": "house-warming-gift", "priority": 100},
            {"keyword": "house warming gifts", "collection": "house-warming-gift", "priority": 100},
            {"keyword": "house warming gift", "collection": "house-warming-gift", "priority": 100},
            {"keyword": "housewarming", "collection": "house-warming-gift", "priority": 100},
            {"keyword": "housewarming gifts", "collection": "house-warming-gift", "priority": 100},
            {"keyword": "housewarming gift", "collection": "house-warming-gift", "priority": 100},
            {"keyword": "corporate gifting", "category": "corporate-gifting", "priority": 90},
            {"keyword": "festival gifts", "category": "festival-gifts", "priority": 90},
            {"keyword": "special gifts", "category": "special-occassion-gifts", "priority": 90},
            {"keyword": "festival gift", "category": "festival-gifts", "priority": 90},
            {"keyword": "special gift", "category": "special-occassion-gifts", "priority": 90},

            # Must-have failed test mappings
            {"keyword": "radha krishna idol", "collection": "radha-krishna", "priority": 100},
            {"keyword": "vishnu lakshmi", "collection": "vishnu-lakshmi", "priority": 100},
            {"keyword": "gomatha wax casting", "collection": "gomatha-wax-casting-idols", "priority": 100},
            {"keyword": "lord balaji stone idols", "collection": "lord-balaji-stone-idols", "priority": 100},
            {"keyword": "laddu gopal wax casting", "collection": "laddu-gopal-wax-casting", "priority": 100},
            {"keyword": "cup saucer", "collection": "cup-and-saucer", "priority": 100},
            {"keyword": "brass glass", "collection": "glass", "priority": 100},
            {"keyword": "teapot", "collection": "tea-pot", "priority": 100},
            {"keyword": "tea pot", "collection": "tea-pot", "priority": 100},
            {"keyword": "aarti lamp", "category": "diyas-and-lamps", "priority": 70},
            {"keyword": "deepam", "category": "diyas-and-lamps", "priority": 70},
            {"keyword": "dhoop holder", "tag": "dhoop-dhani", "priority": 60},
            {"keyword": "pooja stool", "category": "chowki", "priority": 70},
            {"keyword": "pooja bell", "category": "bells", "priority": 80},
            {"keyword": "brass bell", "category": "bells", "priority": 80},
            {"keyword": "bell", "category": "bells", "priority": 70},
        ]

        DEFAULT_TAGS = [
            "Lord Ganesha",
            "Ganapati",
            "Panchamukhi Ganesha",
            "Dancing Ganesha",
            "Lotus Ganesha",
            "Ganesha Diya",
            "Ganesha Wall Hanging",
            "Lord Hanuman",
            "Panchamukhi Hanuman",
            "Lord Krishna",
            "Laddu Gopal",
            "Radha Krishna",
            "Radha Krishna Swing",
            "Lord Rama",
            "Ram Darbar",
            "Lord Shiva",
            "Nataraja",
            "Lord Vishnu",
            "Lord Balaji",
            "Venkateshwara",
            "Lord Murugan",
            "Kartikeya",
            "Ayyappa Swami",
            "Lord Dattatreya",
            "Lord Narasimha",
            "Sai Baba",
            "Khatu Shyam Baba",
            "Khandoba",

            "Lakshmi Devi",
            "Saraswati Devi",
            "Durga Maatha",
            "Radha Devi",
            "Annapurna Devi",
            "Lalitha Maatha",
            "Renuka Maatha",
            "Karumari Amman",

            "Buddha",
            "Laughing Buddha",
            "Rishi",
            "Elephant",
            "Elephant Pair",
            "Lion",
            "Lion Decor",
            "Turtle",
            "Turtle Decor",
            "Horse",
            "Horse Decor",
            "Gomatha",
            "Peacock",
            "Camel",
            "Bullock Cart",
            "Chariot",
            "Vintage Car",
            "Scooter",
            "Jet Fighter Plane",

            "Diya",
            "Akhanda Diya",
            "Swastik Diya",
            "Peacock Diya",
            "Crystal Diya",
            "Oil Lamp",
            "Harathi",
            "Dhoop Dhani",
            "Kalash",
            "Lota",
            "Chowki",
            "Stand",
            "Stool",
            "Singhasan",
            "Throne",
            "Peetam",
            "Asan",

            "Urli",
            "Wall Decor",
            "Table Decor",
            "Office Decor",
            "Temple Decor",
            "Home Decor",
            "Wall Hanging",
            "Wall Hook",
            "Wall Bracket",
            "Bells",
            "Om Symbol",
            "Swastik Symbol",
            "Swastik Decor",
            "Om Trishul",
            "Dashavatara",
            "Kalpavriksha",

            "Cookware",
            "Serveware",
            "Cooking Pot",
            "Cook And Serve Pot",
            "Kerala Serving Pot",
            "Ghee Pot",
            "Tea Pot",
            "Kettle",
            "Copper Glass",
            "Brass Glass",
            "Cup And Saucer",
            "Mug",
            "Drinkware",

            "Wax Casting",
            "Stone Idol",
            "Silver Plated",
            "Brass",
            "Copper",
            "Antique Finish",

            "Ganesh Chaturthi",
            "Navratri",
            "Diwali",
            "Dussehra",
            "Rakhi",
            "Onam",
            "Shivratri",
            "Janmashtami",
            "Holi",
            "Festival Gifts",

            "Corporate Gifting",
            "Wedding Return Gifts",
            "Wedding Anniversary Gifts",
            "Work Anniversary Gifts",
            "House Warming Return Gifts",
            "Pooja Return Gifts",
            "Festival Gifting",
            "Gift Hamper",
            "Special Combo",
            "New Arrival",
            "Special Offer",
        ]

        for tag_name in DEFAULT_TAGS:
            seeds.append({
                "keyword": tag_name.lower(),
                "tag": slugify(tag_name),
                "priority": 60,
            })

        tag_aliases = [
            {"keyword": "ganesha", "tag": "lord-ganesha", "priority": 15},
            {"keyword": "ganesh", "tag": "lord-ganesha", "priority": 15},
            {"keyword": "hanuman", "tag": "lord-hanuman", "priority": 15},
            {"keyword": "krishna", "tag": "lord-krishna", "priority": 15},
            {"keyword": "krishn", "tag": "lord-krishna", "priority": 15},
            {"keyword": "kanha", "tag": "lord-krishna", "priority": 15},
            {"keyword": "kanhaiya", "tag": "lord-krishna", "priority": 15},
            {"keyword": "rama", "tag": "lord-rama", "priority": 15},
            {"keyword": "ram", "tag": "lord-rama", "priority": 15},
            {"keyword": "shiva", "tag": "lord-shiva", "priority": 15},
            {"keyword": "vishnu", "tag": "lord-vishnu", "priority": 15},
            {"keyword": "balaji", "tag": "lord-balaji", "priority": 15},
            {"keyword": "murugan", "tag": "lord-murugan", "priority": 15},
            {"keyword": "ayyappa", "tag": "ayyappa-swami", "priority": 15},
            {"keyword": "om", "tag": "om-symbol", "priority": 15},
            {"keyword": "swastik", "tag": "swastik-symbol", "priority": 15},
            {"keyword": "ayappa", "tag": "ayyappa-swami", "priority": 15},
            {"keyword": "dattatreya", "tag": "lord-dattatreya", "priority": 15},
            {"keyword": "narasimha", "tag": "lord-narasimha", "priority": 15},
            {"keyword": "narsimha", "tag": "lord-narasimha", "priority": 15},
            {"keyword": "lakshmi", "tag": "lakshmi-devi", "priority": 15},
            {"keyword": "laxmi", "tag": "lakshmi-devi", "priority": 15},
            {"keyword": "radha", "tag": "radha-devi", "priority": 15},
            {"keyword": "annapurna", "tag": "annapurna-devi", "priority": 15},
            {"keyword": "saraswati", "tag": "saraswati-devi", "priority": 15},
            {"keyword": "saraswathi", "tag": "saraswati-devi", "priority": 15},
            {"keyword": "durga", "tag": "durga-maatha", "priority": 15},
            {"keyword": "karumari", "tag": "karumari-amman", "priority": 15},
            {"keyword": "annapurna", "tag": "annapurna-devi", "priority": 15},
            {"keyword": "lalitha", "tag": "lalitha-maatha", "priority": 15},
            {"keyword": "lalita", "tag": "lalitha-maatha", "priority": 15},
            {"keyword": "renuka", "tag": "renuka-maatha", "priority": 15},
            {"keyword": "khatu shyam", "tag": "khatu-shyam-baba", "priority": 15},
            {"keyword": "gifting", "tag": "corporate-gifting", "priority": 15},
            {"keyword": "gift", "tag": "gift-hamper", "priority": 15},
            {"keyword": "gifts", "tag": "gift-hamper", "priority": 15},
            {"keyword": "antique", "tag": "antique-finish", "priority": 15},
        ]

        seeds.extend(tag_aliases)

        created = 0
        updated = 0

        for seed in seeds:
            category = None
            collection = None
            tag = None

            if seed.get("category"):
                category = Category.objects.filter(
                    slug=seed["category"],
                    is_active=True
                ).first()

            if seed.get("collection"):
                collection = Collection.objects.filter(
                    slug=seed["collection"],
                    is_active=True
                ).first()

            if seed.get("tag"):
                tag = Tags.objects.filter(
                    slug=seed["tag"],
                    is_active=True
                ).first()

            if not category and not collection and not tag:
                self.stdout.write(
                    self.style.WARNING(
                        f"Skipped: {seed['keyword']} - no mapped object found"
                    )
                )
                continue

            obj, was_created = ChatbotKeyword.objects.get_or_create(
                keyword=seed["keyword"].lower().strip(),
                category=category,
                collection=collection,
                tag=tag,
                defaults={
                    "priority": seed.get("priority", 10),
                    "is_active": True,
                }
            )

            if was_created:
                created += 1
            else:
                obj.priority = seed.get("priority", 10)
                obj.is_active = True
                obj.save(update_fields=["priority", "is_active"])
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Chatbot keywords seeded. Created: {created}, Updated: {updated}"
            )
        )

# Run Command: python manage.py seed_chatbot_keywords