# Generated by Django 6.0.4 on 2026-04-29 12:49

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_image_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=core.models.category_image_rename),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 18, 19, 51, 505683)),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=core.models.product_image_rename),
        ),
    ]
