# Generated by Django 6.0.4 on 2026-05-13 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_vendor_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='breadth',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 12, 51, 8, 65675)),
        ),
    ]
