# Generated by Django 6.0.4 on 2026-05-13 10:38

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_otp_expires_at_alter_productinventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=core.models.collection_image_rename),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 16, 8, 49, 191596)),
        ),
    ]
