# Generated by Django 6.0.4 on 2026-05-13 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_collection_slug_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 18, 18, 38, 531659)),
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, to='core.collection'),
        ),
    ]
