# Generated by Django 6.0.4 on 2026-05-14 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_otp_expires_at_remove_product_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 15, 13, 18, 4, 767595)),
        ),
    ]
