# Generated by Django 6.0.4 on 2026-05-14 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_length_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 15, 13, 42, 59, 196426)),
        ),
    ]
