# Generated by Django 6.0.4 on 2026-05-14 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_collection_product_collections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='scode',
        ),
        migrations.AddField(
            model_name='collection',
            name='scode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 15, 17, 5, 9, 838183)),
        ),
    ]
