# Generated by Django 6.0.4 on 2026-05-16 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_blogcategory_alter_otp_expires_at_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 8, 40, 52, 370204)),
        ),
    ]
