# Generated by Django 6.0.4 on 2026-05-16 09:09

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_order_id_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='unique_code',
            field=models.CharField(default=core.models.code_generator, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='unique_code',
            field=models.CharField(blank=True, default=core.models.code_generator, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 14, 39, 7, 958869)),
        ),
    ]
