# Generated by Django 6.0.4 on 2026-05-16 09:11

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_customeraddress_unique_code_review_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='unique_code',
            field=models.CharField(default=core.models.code_generator, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 14, 41, 8, 984179)),
        ),
        migrations.AlterField(
            model_name='review',
            name='unique_code',
            field=models.CharField(default=core.models.code_generator, editable=False, max_length=255, unique=True),
        ),
    ]
