# Generated by Django 6.0.4 on 2026-05-16 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_customeraddress_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 14, 44, 21, 608459)),
        ),
    ]
