# Generated by Django 6.0.4 on 2026-05-18 11:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tags_alter_otp_expires_at_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collections',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.collection'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 19, 17, 20, 22, 539982)),
        ),
    ]
