# Generated by Django 6.0.4 on 2026-05-26 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_collections',
            field=models.ManyToManyField(blank=True, related_name='grouped_products', to='core.collection'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 15, 29, 3, 353739)),
        ),
    ]
