# Generated by Django 6.0.4 on 2026-05-26 10:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_product_additional_collections_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_collections',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 15, 57, 47, 838535)),
        ),
        migrations.CreateModel(
            name='GiftingCollectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifting_products', to='core.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifting_collections', to='core.product')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'unique_together': {('collection', 'product')},
            },
        ),
    ]
