# Generated by Django 6.0.4 on 2026-06-12 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_order_payment_id_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payu_txnid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 12, 27, 4, 363901)),
        ),
    ]
