# Generated by Django 6.0.4 on 2026-06-12 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_order_payu_txnid_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_awb_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_courier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 13, 21, 36, 285714)),
        ),
    ]
