# Generated by Django 6.0.4 on 2026-06-12 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_order_shiprocket_awb_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 13, 24, 48, 395870)),
        ),
    ]
