# Generated by Django 6.0.4 on 2026-06-12 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_order_shiprocket_response_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 14, 44, 36, 678210)),
        ),
    ]
