# Generated by Django 6.0.4 on 2026-06-13 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_order_is_deleted_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 14, 11, 30, 48, 340533)),
        ),
    ]
