# Generated by Django 6.0.4 on 2026-06-13 06:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_otp_expires_at_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Offline', 'Offline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.order'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 14, 11, 57, 13, 204145)),
        ),
    ]
