# Generated by Django 6.0.4 on 2026-06-13 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_notificationlog_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 14, 13, 3, 3, 586813)),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel'], name='core_notifi_channel_951fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['event'], name='core_notifi_event_88ee07_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='core_notifi_status_33f2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='core_notifi_created_db2a22_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='core_order_payment_6639e3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='core_order_created_912d27_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='core_order_custome_bed536_idx'),
        ),
    ]
