# Generated by Django 6.0.4 on 2026-06-20 07:19

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_chatsession_alter_otp_expires_at_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 12, 49, 40, 178314)),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('Product', 'Product'), ('Shipping', 'Shipping'), ('Payment', 'Payment'), ('Invoice', 'Invoice'), ('Return', 'Return'), ('Care', 'Care'), ('Gifting', 'Gifting')], default='General', max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords for chatbot search', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unique_code', models.CharField(default=core.models.code_generator, editable=False, max_length=255, unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
