# Generated by Django 6.0.4 on 2026-06-20 09:47

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_otp_expires_at_chatbotkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotkeyword',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbotkeyword',
            name='unique_code',
            field=models.CharField(blank=True, default=core.models.code_generator, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 15, 17, 12, 59355)),
        ),
    ]
