# Generated by Django 6.0.4 on 2026-06-20 09:47

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_chatbotkeyword_is_active_chatbotkeyword_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotkeyword',
            name='unique_code',
            field=models.CharField(default=core.models.code_generator, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 15, 17, 51, 450291)),
        ),
    ]
