# Generated by Django 6.0.4 on 2026-06-22 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_chatbotkeyword_unique_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotkeyword',
            name='priority',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 11, 28, 28, 964143)),
        ),
    ]
