# Generated by Django 6.0.4 on 2026-06-22 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_chatbotkeyword_priority_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotkeyword',
            name='keyword',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 12, 26, 6, 645052)),
        ),
    ]
