# Generated by Django 6.0.4 on 2026-06-22 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_chatbotkeyword_keyword_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotkeyword',
            options={'ordering': ['-priority', 'keyword']},
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 13, 1, 36, 780419)),
        ),
        migrations.AlterUniqueTogether(
            name='chatbotkeyword',
            unique_together={('keyword', 'category', 'collection', 'tag')},
        ),
    ]
