# Generated by Django 6.0.4 on 2026-06-22 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_chatbotkeyword_options_alter_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 23, 17, 1, 10, 458646)),
        ),
    ]
