# Generated by Django 6.0.4 on 2026-06-24 16:52

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_otp_expires_at_productbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundle',
            name='unique_code',
            field=models.CharField(blank=True, default=core.models.code_generator, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 25, 22, 21, 58, 338055)),
        ),
    ]
