# Generated by Django 6.0.4 on 2026-06-25 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_newsevent_bundle_newsevent_clicks_newsevent_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 26, 11, 42, 14, 825924)),
        ),
    ]
