# Generated by Django 6.0.4 on 2026-06-25 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_review_is_featured_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 26, 11, 44, 32, 546627)),
        ),
    ]
