# Generated by Django 6.0.4 on 2026-06-25 09:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_product_meta_description_product_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.productbundle'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 26, 14, 47, 16, 625749)),
        ),
    ]
