# Generated by Django 6.0.4 on 2026-06-25 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_faq_bundle_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsevent',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='newsevent',
            name='product',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 26, 15, 41, 57, 615384)),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='bundle',
            field=models.ManyToManyField(blank=True, to='core.productbundle'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='product',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
