# Generated by Django 6.0.4 on 2026-06-25 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_otp_expires_at_chatbotsearchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='source',
            field=models.CharField(choices=[('Chatbot', 'Chatbot'), ('Manual', 'Manual'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Phone', 'Phone')], default='Manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 26, 16, 11, 11, 523434)),
        ),
    ]
