# Generated by Django 6.0.4 on 2026-06-26 10:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_supportticket_source_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotsearchlog',
            old_name='matched_product',
            new_name='selected_product',
        ),
        migrations.AddField(
            model_name='chatbotsearchlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='chatbotsearchlog',
            name='matched_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productbundle'),
        ),
        migrations.AddField(
            model_name='chatbotsearchlog',
            name='matched_products',
            field=models.ManyToManyField(blank=True, related_name='chatbot_logs', to='core.product'),
        ),
        migrations.AddField(
            model_name='chatbotsearchlog',
            name='support_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supportticket'),
        ),
        migrations.AlterField(
            model_name='chatbotsearchlog',
            name='query',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='chatbotsearchlog',
            name='result_type',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('PRODUCT', 'PRODUCT'), ('BUNDLE', 'BUNDLE'), ('SUPPORT', 'SUPPORT'), ('EMPTY', 'EMPTY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 27, 16, 7, 35, 803516)),
        ),
    ]
