# Generated by Django 6.0.4 on 2026-06-27 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_chatbotsearchlog_result_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotsearchlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='chatbotsearchlog',
            name='result_type',
            field=models.CharField(choices=[('FAQ', 'FAQ'), ('PRODUCT', 'PRODUCT'), ('BUNDLE', 'BUNDLE'), ('SUPPORT', 'SUPPORT'), ('EMPTY', 'EMPTY'), ('TRACK_ORDER', 'TRACK_ORDER'), ('INVOICE', 'INVOICE')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 28, 13, 5, 26, 890638)),
        ),
        migrations.AddIndex(
            model_name='chatbotsearchlog',
            index=models.Index(fields=['created_at'], name='core_chatbo_created_bb6d61_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsearchlog',
            index=models.Index(fields=['result_type'], name='core_chatbo_result__2ab4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsearchlog',
            index=models.Index(fields=['customer'], name='core_chatbo_custome_4e23ad_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotsearchlog',
            index=models.Index(fields=['session'], name='core_chatbo_session_e40546_idx'),
        ),
    ]
