# Generated by Django 6.0.4 on 2026-07-01 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_product_is_deleted_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundle',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 2, 11, 48, 52, 29921)),
        ),
    ]
