# Generated by Django 6.0.4 on 2026-07-02 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_productbundle_short_description_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 3, 12, 27, 3, 469368)),
        ),
    ]
