# Generated by Django 6.0.4 on 2026-07-02 11:58

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='unique_code',
            field=models.CharField(default=core.models.code_generator, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 3, 17, 28, 14, 67931)),
        ),
    ]
