# Generated by Django 6.0.4 on 2026-07-02 11:58

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_blogcategory_unique_code_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='unique_code',
            field=models.CharField(blank=True, default=core.models.code_generator, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 3, 17, 28, 45, 801990)),
        ),
    ]
