# Generated by Django 6.0.4 on 2026-07-02 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_blog_unique_code_alter_blogcategory_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 3, 17, 32, 26, 856203)),
        ),
    ]
