# Generated by Django 6.0.4 on 2026-07-04 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_blogcategory_alter_otp_expires_at_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbundle',
            name='bundle_type',
            field=models.CharField(choices=[('pooja', 'Pooja'), ('festival', 'Festival'), ('gift', 'Gift'), ('decor', 'Decor'), ('kitchen', 'Kitchen'), ('premium', 'Premium')], default='pooja', max_length=50),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 5, 15, 11, 11, 710378)),
        ),
    ]
