# Generated by Django 6.0.4 on 2026-07-06 06:11

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_productbundle_bundle_type_productbundle_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=core.models.blog_image_rename),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 7, 11, 41, 59, 756005)),
        ),
    ]
