# Generated by Django 6.0.4 on 2026-07-08 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_blog_thumbnail_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='core.blog'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Product', 'Product'), ('Shipping', 'Shipping'), ('Payment', 'Payment'), ('Invoice', 'Invoice'), ('Return', 'Return'), ('Care', 'Care'), ('Gifting', 'Gifting'), ('Blog', 'Blog')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 9, 17, 9, 35, 515353)),
        ),
    ]
